package mx.gob.imss.cit.mjlssc.persistence.entity;
// Generated 28 mar. 2022 12:41:49 by Hibernate Tools 3.6.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SsccTipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "SSCC_TIPO_DOCUMENTO")
public class SsccTipoDocumento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1829950260413672000L;
	private Long cveTipoDocumento;
	private String desTipoDocumento;
	private Date fecAlta;
	private Date fecBaja;
	private Date fecModifica;
	private String cveUsuarioAlta;
	private String cveUsuarioBaja;
	private String cveUsuarioModifica;
	private Set<DocumentoDigitalizado> ssctDocumentoDigitalizadoAmparoIndirectos = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CVE_TIPO_DOCUMENTO", unique = true, nullable = false)
	public Long getCveTipoDocumento() {
		return this.cveTipoDocumento;
	}

	public void setCveTipoDocumento(Long cveTipoDocumento) {
		this.cveTipoDocumento = cveTipoDocumento;
	}

	@Column(name = "DES_TIPO_DOCUMENTO", nullable = false, length = 200)
	public String getDesTipoDocumento() {
		return this.desTipoDocumento;
	}

	public void setDesTipoDocumento(String desTipoDocumento) {
		this.desTipoDocumento = desTipoDocumento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ALTA", nullable = false, length = 26)
	public Date getFecAlta() {
		return this.fecAlta;
	}

	public void setFecAlta(Date fecAlta) {
		this.fecAlta = fecAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_BAJA", length = 26)
	public Date getFecBaja() {
		return this.fecBaja;
	}

	public void setFecBaja(Date fecBaja) {
		this.fecBaja = fecBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MODIFICA", length = 26)
	public Date getFecModifica() {
		return this.fecModifica;
	}

	public void setFecModifica(Date fecModifica) {
		this.fecModifica = fecModifica;
	}

	@Column(name = "CVE_USUARIO_ALTA", nullable = false, length = 60)
	public String getCveUsuarioAlta() {
		return this.cveUsuarioAlta;
	}

	public void setCveUsuarioAlta(String cveUsuarioAlta) {
		this.cveUsuarioAlta = cveUsuarioAlta;
	}

	@Column(name = "CVE_USUARIO_BAJA", length = 60)
	public String getCveUsuarioBaja() {
		return this.cveUsuarioBaja;
	}

	public void setCveUsuarioBaja(String cveUsuarioBaja) {
		this.cveUsuarioBaja = cveUsuarioBaja;
	}

	@Column(name = "CVE_USUARIO_MODIFICA", length = 60)
	public String getCveUsuarioModifica() {
		return this.cveUsuarioModifica;
	}

	public void setCveUsuarioModifica(String cveUsuarioModifica) {
		this.cveUsuarioModifica = cveUsuarioModifica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ssccTipoDocumento")
	public Set<DocumentoDigitalizado> getSsctDocumentoDigitalizadoAmparoIndirectos() {
		return this.ssctDocumentoDigitalizadoAmparoIndirectos;
	}

	public void setSsctDocumentoDigitalizadoAmparoIndirectos(
			Set<DocumentoDigitalizado> ssctDocumentoDigitalizadoAmparoIndirectos) {
		this.ssctDocumentoDigitalizadoAmparoIndirectos = ssctDocumentoDigitalizadoAmparoIndirectos;
	}

}
