package mx.gob.imss.cit.mjlssc.persistence.entity;
// Generated 19 abr. 2022 11:34:20 by Hibernate Tools 3.6.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import mx.gob.imss.cit.mjlssc.component.DataBaseShemaConf;

/**
 * SsccDelegacion generated by hbm2java
 */
@Entity
@Table(name = "SSCC_DELEGACION", catalog = DataBaseShemaConf.SCHEMANML)
public class SsccDelegacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3922451447146516578L;
	private Integer cveDelegacion;
	private String desDelegacion;
	private String refAbreviacion;
	private Date fecAlta;
	private Date fecBaja;
	private Date fecModifica;
	private String cveUsuarioAlta;
	private String cveUsuarioBaja;
	private String cveUsuarioModifica;

	public SsccDelegacion() {
	}

	public SsccDelegacion(Date fecAlta, String cveUsuarioAlta) {
		this.fecAlta = fecAlta;
		this.cveUsuarioAlta = cveUsuarioAlta;
	}

	public SsccDelegacion(String desDelegacion, String refAbreviacion, Date fecAlta, Date fecBaja, Date fecModifica,
			String cveUsuarioAlta, String cveUsuarioBaja, String cveUsuarioModifica) {
		this.desDelegacion = desDelegacion;
		this.refAbreviacion = refAbreviacion;
		this.fecAlta = fecAlta;
		this.fecBaja = fecBaja;
		this.fecModifica = fecModifica;
		this.cveUsuarioAlta = cveUsuarioAlta;
		this.cveUsuarioBaja = cveUsuarioBaja;
		this.cveUsuarioModifica = cveUsuarioModifica;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CVE_DELEGACION", unique = true, nullable = false)
	public Integer getCveDelegacion() {
		return this.cveDelegacion;
	}

	public void setCveDelegacion(Integer cveDelegacion) {
		this.cveDelegacion = cveDelegacion;
	}

	@Column(name = "DES_DELEGACION", length = 30)
	public String getDesDelegacion() {
		return this.desDelegacion;
	}

	public void setDesDelegacion(String desDelegacion) {
		this.desDelegacion = desDelegacion;
	}

	@Column(name = "REF_ABREVIACION", length = 3)
	public String getRefAbreviacion() {
		return this.refAbreviacion;
	}

	public void setRefAbreviacion(String refAbreviacion) {
		this.refAbreviacion = refAbreviacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ALTA", nullable = false, length = 26)
	public Date getFecAlta() {
		return this.fecAlta;
	}

	public void setFecAlta(Date fecAlta) {
		this.fecAlta = fecAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_BAJA", length = 26)
	public Date getFecBaja() {
		return this.fecBaja;
	}

	public void setFecBaja(Date fecBaja) {
		this.fecBaja = fecBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_MODIFICA", length = 26)
	public Date getFecModifica() {
		return this.fecModifica;
	}

	public void setFecModifica(Date fecModifica) {
		this.fecModifica = fecModifica;
	}

	@Column(name = "CVE_USUARIO_ALTA", nullable = false, length = 60)
	public String getCveUsuarioAlta() {
		return this.cveUsuarioAlta;
	}

	public void setCveUsuarioAlta(String cveUsuarioAlta) {
		this.cveUsuarioAlta = cveUsuarioAlta;
	}

	@Column(name = "CVE_USUARIO_BAJA", length = 60)
	public String getCveUsuarioBaja() {
		return this.cveUsuarioBaja;
	}

	public void setCveUsuarioBaja(String cveUsuarioBaja) {
		this.cveUsuarioBaja = cveUsuarioBaja;
	}

	@Column(name = "CVE_USUARIO_MODIFICA", length = 60)
	public String getCveUsuarioModifica() {
		return this.cveUsuarioModifica;
	}

	public void setCveUsuarioModifica(String cveUsuarioModifica) {
		this.cveUsuarioModifica = cveUsuarioModifica;
	}

}
